/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/404`; params?: Router.UnknownInputParams; } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiketsu` | `/seiketsu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiri` | `/seiri`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiso` | `/seiso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiton` | `/seiton`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shitsuke` | `/shitsuke`; params?: Router.UnknownInputParams; } | { pathname: `/utils/CustomAlert`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/404`; params?: Router.UnknownOutputParams; } | { pathname: `/constants`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/seiketsu` | `/seiketsu`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/seiri` | `/seiri`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/seiso` | `/seiso`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/seiton` | `/seiton`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/shitsuke` | `/shitsuke`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/CustomAlert`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/404${`?${string}` | `#${string}` | ''}` | `/constants${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/seiketsu${`?${string}` | `#${string}` | ''}` | `/seiketsu${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/seiri${`?${string}` | `#${string}` | ''}` | `/seiri${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/seiso${`?${string}` | `#${string}` | ''}` | `/seiso${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/seiton${`?${string}` | `#${string}` | ''}` | `/seiton${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/shitsuke${`?${string}` | `#${string}` | ''}` | `/shitsuke${`?${string}` | `#${string}` | ''}` | `/utils/CustomAlert${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/404`; params?: Router.UnknownInputParams; } | { pathname: `/constants`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiketsu` | `/seiketsu`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiri` | `/seiri`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiso` | `/seiso`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/seiton` | `/seiton`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/shitsuke` | `/shitsuke`; params?: Router.UnknownInputParams; } | { pathname: `/utils/CustomAlert`; params?: Router.UnknownInputParams; };
    }
  }
}
